CREATE TABLE Attraction(
	ID INT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) UNIQUE,
    City_ID INT,
    Description VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (City_ID) REFERENCES City(ID)
) AUTO_INCREMENT = 1000;

CREATE TABLE City(
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(100) UNIQUE, 
    PRIMARY KEY (ID)
) AUTO_INCREMENT = 100;
    
CREATE TABLE Tags(
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(50), 
	Attraction_ID INT,
	PRIMARY KEY (ID)
) AUTO_INCREMENT = 1;
        
CREATE TABLE Tag_Attraction(
	Tag_ID INT NOT NULL,
	Attraction_ID INT NOT NULL,
	PRIMARY KEY (Tag_ID, Attraction_ID),
	FOREIGN KEY (Tag_ID) REFERENCES Tags(ID) ON DELETE CASCADE,
	FOREIGN KEY (Attraction_ID) REFERENCES Attraction(ID) ON DELETE CASCADE
);